# fly.toml app configuration file for spab
app = "spab"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"  # Указываем Dockerfile для сборки контейнера

[mounts]
  source = "data"
  destination = "/app/data"

[env]
  TOKEN = "ВАШ_ТЕЛЕГРАМ_ТОКЕН"  # Ваш токен Telegram-бота

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
